/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.returning;

import dao.ReaderDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Reader;
import model.Returning;
import model.User;

/**
 *
 * @author admin
 */
public class ScanReaderFrm extends javax.swing.JFrame implements ActionListener{
    private User user;
    private Reader reader = new Reader();
    /**
     * 
     * Creates new form ScanReaderFrm
     */
    public ScanReaderFrm(User user) {
        this.user = user;
        initComponents();
//        txtInfo.setText(user.getName());
        
//        this.addKeyListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Scanning Reader Card ...");

        jLabel2.setText("Quet the doc gia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInfo)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInfo)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                Returning returning = new Returning();
                returning.setUser(user);
                ReaderDAO rd = new ReaderDAO();
                this.reader = rd.scanReader(reader.getCardNumber());
                if(this.reader != null)
                {
    //                System.out.println("sf");
                    returning.setReader(this.reader);
                    (new ReturnBookFrm(returning)).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, 
                          "Không tìm thấy độc giả!");
                    this.reader = new Reader();
                    this.reader.setCardNumber("");
                }
            }
            else {
                this.reader.setCardNumber(this.reader.getCardNumber() + 
                        Character.toString(evt.getKeyChar())); 
                System.out.println(this.reader.getCardNumber());
            }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScanReaderFrm(new User()).setVisible(true);
            }
        });
        
        /* Create and display the form */
    }

    @Override
    public void actionPerformed(ActionEvent e) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtInfo;
    // End of variables declaration//GEN-END:variables
}
